epochs: 40
lr: 0.000005
lr_backbone_multiplier: 1.0
lr_head_multiplier: 10.0
weight_decay: 0.01
betas: [0.9, 0.999]
scheduler:
  type: poly
  power: 0.9
save_path: ${hydra:run.dir}
save_latest: true
log_interval: 100
torch_compile: true
notes: ""
